export const defaultGlobalStyle = {
  global: {
    backgroundColor: '#e8f0fe',
    width: '600px',
    marginTop: '0',
    marginBottom: '0',
  },
  text: {
    minHeight: '25px',
    paddingTop: '10px',
    paddingBottom: '10px',
    paddingLeft: '10px',
    paddingRight: '10px',
    fontSize: '16px',
    fontWeight: 500,
    color: '#000000',
    textAlign: 'left',
    fontFamily: 'Arial, sans-serif',
  },
  image: {
    minHeight: '25px',
    paddingTop: '0',
    paddingBottom: '0',
    paddingLeft: '0',
    paddingRight: '0',
  },
  button: {
    backgroundColor: '#000000',
    color: '#ffffff',
    marginTop: '10px',
    marginBottom: '10px',
    paddingTop: '10px',
    paddingBottom: '10px',
    paddingLeft: '10px',
    paddingRight: '10px',
    borderRadius: '5px',
    fontFamily: 'Arial, sans-serif',
  },
  container: {
    backgroundColor: '#ffffff',
    textAlign: 'center',
  },
  spacer: {
    height: '25px',
    backgroundColor: '#red',
  },
  divider: {
    minHeight: '25px',
    borderType: 'solid',
    borderTopWidth: '2px',
    borderColor: '#000000',
    borderBottom: 'none',
    borderLeft: 'none',
    borderRight: 'none',
  },
  section: {
    minHeight: '25px',
    paddingTop: '20px',
    paddingBottom: '10px',
    backgroundColor: '#ffffff',
  },
};
